server:
  tomcat:
    uri-encoding: UTF-8
    # 配置线程数
    threads:
      max: 200
      min-spare: 30
    # 设置连接超时时间
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /OAmangerOS

spring:
  datasource:
    # 设置数据源为阿里巴巴的druid数据连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: qaz741
      initialSize: 8
      max-active: 16
      min-idle: 8
      max-wait: 6000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: abc123456

mybatis:
  config-location: classpath*:mapper/*.xml
  type-aliases-package: com.example.oamanageros.wx.db.pojo
  configuration:
    # 设置sql日志输出 方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.oamanageros.wx.db.dao: warn
  pattern:
    # 设置输出格式
    console: "%d{HH:mm:ss}  %-5level  %msg%n"